# -*- coding: utf-8 -*-
"""Morphology_embed.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1uZUe-O4GgKuMK1FfbAV7xztgtD4lWEEC
"""

import stanza
import argparse
parser = argparse.ArgumentParser(description='A tutorial of argparse!')
parser.add_argument("--language")
parser.add_argument("--inputfile")
parser.add_argument("--outputfile")
args = parser.parse_args()
lang = args.language
inp_f=args.inputfile
opt_f=args.outputfile
fr=open(inp_f,'r+')
entxt=fr.read()
nlp = stanza.Pipeline(lang=lang, processors='tokenize,pos',use_gpu=True, pos_batch_size=2000)
doc = nlp(entxt)
print(len(doc.sentences))
fd=open(opt_f,'a+')
featlst=['Case', 'AdpType', 'Gender', 'Mood', 'Person', 'PronType', 'Tense', 'VerbForm', 'Voice', 'Number']
i=0
for sent in doc.sentences:
  wrdlst=[]
  print(i)
  i=i+1
  for word in sent.words:
    formatted_word=f'{word.text}+{word.upos}'
    if word.feats:
      morph_feat_dict = dict(x.split("=") for x in word.feats.split("|"))
      feat_form=''
      for feat in featlst:
        if feat in morph_feat_dict:
          feat_form=feat_form+'+'+morph_feat_dict[feat]
        else:
          feat_form=feat_form+'+'+'-'
      #print(feat_form)
      #print(d)
    else:
      feat_form='+-+-+-+-+-+-+-+-+-+-'
    formatted_word=formatted_word+feat_form
    wrdlst.append(formatted_word)
    #print(formatted_word)
  formatted_sent=' '.join(wrdlst)
  fd.write(formatted_sent)
  fd.write("\n")
  
fd.close()
print("file formatting has been done for language:",lang)
